### ISSUE TITLE
Multiple event JSON-LD render only one

### ISSUE THREAD

**Issue by SimonHausdorf** [garmeeh/next-seo#1040]
**Describe the bug**
A main event page which lists multiple events can have multiple event schemas. Currently when adding multiple `<EventJsonLd />` it will only render one in the head of the page.

**Reproduction**
Place multiple `<EventJsonLd />` on the same page

**Expected behavior**
Should render multiple schemas for the events

**Comment by SimonHausdorf** [comment]
Sorry, my mistake. It works without issues.

**Comment by garmeeh** [comment]
Hey @SimonHausdorf in general it is advised to only have a single JSON-LD per type. 

For example on a search page of events you would generally not render the `EventJsonLd` for each one. You would instead render the `EventJsonLd` for the event detail page that you would click through. 

However, if you really want to render multiple you can use `keyOverride`.

The reason only one is rendered is due to each one by default having the same key under the hood. So for your `keyOverride` for each will need to be unique. It can be anything, even just 1,2,3 etc.

**Comment by SimonHausdorf** [comment]
Thanks @garmeeh 

I am not sure if it's correct to say that it's advised to have only 1 JSON-LD per type.
To achieve a google result like this you need to specify multiple JSON-LD per type.
<img width="643" alt="image" src="https://user-images.githubusercontent.com/1446685/197024123-67a82745-ab37-439b-80d1-52c54ec3ad58.png">

**Comment by garmeeh** [comment]
So they already have JSON-LD for the event on each event page, for example: https://bravenewcoin.com/events/dcom-future-summit-london has the same json-ld as it does on the list page. 

So google has all the info it needs from that and there should be no need for the duplication. 

It is the same principle as for products. Although the Carousel was introduced for listings of products. 

With SEO it can never hurt to have a little extra coverage anyway and it always changes so my assumptions could very well be out of date 😅 

Thanks @SimonHausdorf.

**Comment by SimonHausdorf** [comment]
I was reading about it again and tried to find some official guidelines. What I can say is that for our project it hat the same result as shown in the screenshot and multiple upcoming events were listed. As example we are listing only cryptocurrency related events so if someone is searching for "cryptocurrency events in city" our collection page should show up listing the last 3 upcoming events which I think is good.

However, the google guidelines say the following:
> Currently, the event experience on Google only supports pages that focus on a single event. We recommend focusing on adding markup to your event posting pages instead of pages that list schedules or multiple events.
> 
> https://developers.google.com/search/docs/appearance/structured-data/event#technical-guidelines

So far, the results on google listing multiple events on a collection page had all multiple JSON-JD defined on their page for all the listed events.

So, it says unclear for me what is right or wrong but I could achieve the expected result with adding multiple event schemas.

**Comment by garmeeh** [comment]
@SimonHausdorf Would you mind sharing how you currently implement multiple events? (assuming you are using next-seo now with keyOverride)

Is it something like:

```
{events.map((event, index) => <EventJsonLd  {...event} keyOverride={index} />)}
```

🤔 Maybe I should  update the core of the library support multiple on all of the JSON-LD's.

Something like:

```
 <EventJsonLd  events={events} />
```

which would output:

```
<script type="application/ld+json">
  [
    {
      "@context": "http://schema.org",
      "@type": "Event",
      "name": "Evnet Name",
    },
    {
      "@context": "http://schema.org",
      "@type": "Event",
      "name": "Evnet Name",
    },
    {
      "@context": "http://schema.org",
      "@type": "Event",
      "name": "Evnet Name",
    },
    {
      "@context": "http://schema.org",
      "@type": "Event",
      "name": "Evnet Name",
    }
  ]
</script>
```

rather than multiple script tags.

`<EventJsonLd />` would still support just props then for a single event to be backwards compatible.

**Comment by SimonHausdorf** [comment]
> Is it something like:
> 
> ```
> {events.map((event, index) => <EventJsonLd  {...event} keyOverride={index} />)}
> ```

Exactly like that. Index key can indeed vary but the idea is the same.
I think that the suggested output makes sense.
