### ISSUE TITLE
open graph video url, secure_url and video type missing

### ISSUE THREAD

**Issue by kmhari** [garmeeh/next-seo#347]
Need ability to add more details about the open graph video like `og:video:url`  `og:video:secure_url` and `og:video:type`

If this can be added already then great.
If not and you're looking to add these and looking for contributor then i'm in.

**Comment by garmeeh** [comment]
Hey @kmhari these are currently not in `next-seo` but a pull request to add them would be brilliant 😄

**Comment by TomPradat** [comment]
Hey there, was this added yet ? Else can I work on this ?

**Comment by Vladimir1f** [comment]
Work, work my friend23:46, 28 октября 2020 г., TomPradat <notifications@github.com>:
Hey there, was this added yet ? If not can I work on this ?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты
