### ISSUE TITLE
Set language and keywords with next-seo

### ISSUE THREAD

**Issue by IRediTOTO** [garmeeh/next-seo#411]
Hi, just found next-seo, thank you for create this, look so easy to setup
I want to ask about language
how can set `lang="en-EN"` and keywords?
I tried like bellow but it didn't show
 ```
keywords: item.tags ? item.tags : item.nameItem.split(" "),
         key: item.tags ? item.tags : item.nameItem.split(" "),
         languageAlternates:[{
            hrefLang: 'en-EN',
            href: process.env.WEB_URI,
          }],
```
![image](https://user-images.githubusercontent.com/15695252/86534652-2208d500-bf04-11ea-8614-370a475f343b.png)

**Comment by garmeeh** [comment]
Hey @IRediTOTO what you have for  `languageAlternates` looks valid. 

I suspect adding the `keywords` prop may be causing an issue. It is not supported by `next-seo`. This is mainly due to it no longer being used by search engines such as google. 

See in [here](https://github.com/garmeeh/next-seo#additional-meta-tags) in the docs on how you could add them if you wanted, but for SEO purposes they are not very relevant.
