### ISSUE TITLE
Can't find docs for "WebSite" schema

### ISSUE THREAD

**Issue by omar-dulaimi** [garmeeh/next-seo#543]
Hello,
any luck that the WebSite schema is actually supported by the library and just missing its docs?
I couldn't find it anywhere, so perhaps there's a reason for that.

Edit:
I'd like to work on a PR for this if possible.

**Comment by garmeeh** [comment]
Hey @omar-dulaimi do you have an example of what you would propose was added?

**Comment by omar-dulaimi** [comment]
Hello @garmeeh 
This is the one: https://developers.google.com/search/docs/data-types/sitelinks-searchbox

Can I work on it? and any idea how you guys decide if a field is required since Schema.org doesn't have such thing?

**Comment by garmeeh** [comment]
Hey @omar-dulaimi a pull request would be very welcome. There is another issue opened refers to Sitelinks you can see it here #539. I will close this issue so there is not a duplicate. If you are going to work on it could you a comment on #539 to say you are going to work on SiteLinks so that there is a not a duplication of effort. 

As for the required properties, I normally aim to please Google so I use there docs as source of truth. So you can see this section for required properties: https://developers.google.com/search/docs/data-types/sitelinks-searchbox
