### ISSUE TITLE
Variable scoping causing issues between renders

### ISSUE THREAD

**Issue by rppld** [garmeeh/next-seo#65]
For example, in our case page A has a `titleTemplate` defined and page B doesn’t. If page B would be rendered _after_ page A, the page title would still follow the template because it was served from memory. The root cause is the `defaults` object inside `buildTags.jsx` defined in global scope.

I created a PR to address this issue https://github.com/garmeeh/next-seo/pull/64

The wrong behaviour is also visible in your own snapshots, where the title of "Article SEO" would contain the template defined in an earlier test when it shouldn’t, see https://github.com/garmeeh/next-seo/pull/64/commits/fee129e487bc13f171417f5ea6dd0fb1d717bae3. Let me know if this is enough for a reproduction, otherwise I can also create a sandbox or so ✌️

**Comment by garmeeh** [comment]
Hey @rppld, thanks for the PR. This is a tough one. This is expected behaviour as these are global defaults. I suppose in my head they were only ever going to be set in the `_app.js` and not on a per page basis. 

For example in your case for Page A, you don't need a `titleTemplate` as you can set the title string and include what ever your `titleTemplate` was going to be. Then in Page B you can now set your title with no issues. 

This doesn't come across very clear from the docs or examples maybe. This is something I hope to address in V2 which is a WIP at the moment. 

I definitely agree that this side effect is not great.

**Comment by rppld** [comment]
Yeah, thought so when I broke SEO overrides in the Cypress tests. Think my mental model about this was off. We’re using page templates, for each of them we’ve also defined title templates. Closing this in anticipation of v2 ☺️
