### ISSUE TITLE
Only <DefaultSeo> is exported when running next export

### ISSUE THREAD

**Issue by travis-south** [garmeeh/next-seo#714]
Hi,

It was really easy and helpful to use `next-seo` and I'm loving it. I'm just having issue when I'm exporting may project as a static page wherein only the values defined in my `_app.tsx`'s `<DefaultSeo />` and not the page specific `<NextSeo />`.

Is this a bug or it's just not supported at the moment?

Unfortunately, I'm just building and exporting my site and deploying it to S3 for static hosting. Is there a way that the page specific's `<NextSeo />` config can be exported as well?

Thanks.

**Comment by travis-south** [comment]
Still relevant.

**Comment by aksperiod** [comment]
I'm experiencing this as well, seems like a huge bug.

**Comment by travis-south** [comment]
Yes

**Comment by travis-south** [comment]
Yes, still relevant.

**Comment by travis-south** [comment]
Yes

**Comment by samesamestudio** [comment]
I'm experiencing the same issue. Anyone has any fixes yet?

**Comment by gaberogan** [comment]
I'm reproducing this when overriding renderPage with with renderToStringWithData, not sure why yet

**Comment by cullylarson** [comment]
I'm having seemingly a similar issue, but with server rendered pages (i.e. `getServerSideProps` pages). The page title/meta from `_app` is being generated instead of the page-specific values. Though if I try using `next/head` instead of `next-seo` the same thing happens. So maybe this isn't a next-seo issue? @travis-south Have you tried using `next/head`? Does the same problem happen for you?

**Comment by gstrobl** [comment]
@travis-south did you fixed it?
