### ISSUE TITLE
Render a default canonical tag

### ISSUE THREAD

**Issue by alecrae** [garmeeh/next-seo#86]
It would be convenient to have the canonical tag be rendered with the current page url by default if none is passed into the config. This would save having to manually specify it for every page, (which is essentially duplicating the `pages/` structure). I can create a PR if this would be an acceptable idea

**Comment by adonig** [comment]
I did the following to get a default canonical tag:

seo.config.js
```
export default props => {
    const url = `https://example.org${props.router.asPath}`
    return {
        canonical: url,
        openGraph: {
            url,
            /* ... */
        },
        /* ... */
    };
};
```

pages/_app.js
```
import { DefaultSeo } from "next-seo";
import useSeoConfig from "../seo.config.js";

class MyApp extends App {
    render() {
        const seoConfig = useSeoConfig(this.props);
        return (
            <Container>
                <DefaultSeo {...seoConfig} />
                {/* ... */}
            </Container>
        );
    }
}
```

**Comment by garmeeh** [comment]
I feel this could be a dangerous default to have so not going to implement. Above solution would give the same behaviour with little overhead.

**Comment by jpedroschmitz** [comment]
I'd recommend removing all query parameters from the `asPath` value. Example:

```js
const pathWithoutQueryParams = router.asPath.split('?')[0];

return (
  <DefaultSeo
    {...defaultSeo}
    canonical={`${defaultSeoUrl}${pathWithoutQueryParams}`}
  />
);
```

Important note: If the query parameter is used to specify the content loaded onto the page, it should be included in your canonical URL. That's why the best solution is defining the canonical URL per page. By default, I always remove since I don't use query parameters for IDs or slugs.

**Comment by GrayGalaxy** [comment]
Instead of a default canonical tag can we have a template that start with the website URL ?

For example, in `/about` page
```
import { NextSeo} from "next-seo";

function AboutPage {
  return (
    <Container>
        <NextSeo canonical='about' />
        {/* ... */}
    </Container>
  );
}
```

... that ultimately creates `<link rel="canonical" href="https://somewebsite.com/about">`

where we can provide the site_url in config file.

I assume this approach would be better than a default canonical tag.
